name: Build, Push, and Deploy Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'chatbot/**'
      - 'openai/**'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - folder: chatbot
            container-app-name: 'ca-chatbot-'  # Adjusted to use as prefix
          - folder: openai
            container-app-name: 'ca-openai-'  # Adjusted to use as prefix
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r ./${{ matrix.folder }}/requirements.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.folder }}
          file: ./${{ matrix.folder }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.folder }}:latest
        env:
          DOCKER_CONTENT_TRUST: 1
          DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE: ${{ secrets.DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps matching a specific name pattern
        run: |
          prefix="${{ matrix.container-app-name }}"  # Use matrix value as prefix
          apps=$(az containerapp list --query "[?starts_with(name, '${prefix}')].name" --output tsv)
          for app in $apps; do
            echo "Updating container app: $app"
            az containerapp update --name "$app" \
                                   --resource-group "rg-ilovejojo" \
                                   --image ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.folder }}:latest
          done

      - name: Azure Logout
        run: az logout
